### ISSUE TITLE
Log  can't show!

### ISSUE THREAD

**Issue by sr71k** [nubomedia-vtt/nubo-test#1]
Sometimes i cant't  get the log when the method " onRoomNotification"  running.
How can I solve this problem?

**Comment by sr71k** [comment]
@jpsjanne

**Comment by jpsjanne** [comment]
So your problem is that you are not seeing any log messages in adb if invoked inside onRoomNotification? Can you give some example code which shows this issue?

Edit. Sorry a second I thought this was posted on the room API repo. So there are two onRoomNotifications, in MainActivity and on PeerVideoActivity. Have you done any modifications into these functions?

**Comment by jpsjanne** [comment]
I am closing this issue as outdated since there was no further information on the issue.
