### ISSUE TITLE
Error code 304

### ISSUE THREAD

**Issue by xsf2016** [nubomedia-vtt/nubo-test#2]
Sometimes, i get error code 304 - "can't add existing ice candidates to null webrtcendpoint", why?

**Comment by xsf2016** [comment]
？？

**Comment by jpsjanne** [comment]
Hi, so far we haven't been able to come up the exact reason for this issue. It is most likely a race condition between the room API and webrtc API. I've been able to reproduce the issue a couple of times but since it's so unpredictable it makes it difficult to debug. I will keep you updated if we get it fixed.

**Comment by xsf2016** [comment]
ok,
thanks!

**Comment by xsf2016** [comment]
Hi, I have solved this problem.
Do not take "sendReceiveVideoFrom"  run on UiThread in the interface function of "onLocalSdpOfferGenerated",  remove runOnUiThread can solve it.

**Comment by jpsjanne** [comment]
Hi, thank you very much for figuring this out! This issue is now [Fixed](https://github.com/nubomedia-vtt/nubo-test/commit/86abb406d84893f3e6221d8e75659dada6941541)
